version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "fubar"
    IMAGE_TAG: "latest"
    AWS_ACCOUNT_ID: "776648872426"
    AWS_DEFAULT_REGION: "eu-west-2"
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - curl -LO https://redirector.gvt1.com/edgedl/go/go1.9.2.linux-amd64.tar.gz
      - tar -xvzf go1.9.2.linux-amd64.tar.gz
      - mv go/ /opt
      - export PATH="/opt/go/bin/":$PATH
      - export PATH=$PATH:$(go env GOPATH)/bin
      - echo "GOPATH = $GOPATH"
      - mkdir -p "$(go env GOPATH)/{src,bin,pkg}"
      - make build
      - docker build -t $IMAGE_REPO_NAME:latest .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
