version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "fubar"
    IMAGE_TAG: "latest"
    AWS_ACCOUNT_ID: "776648872426"
    AWS_DEFAULT_REGION: "eu-west-2"
    PACKAGE: "github.com/reaandrew/fubar"
    GOLANG_VERSION: "1.9.2"
phases:
  install:
    commands:
      - curl -LO "https://redirector.gvt1.com/edgedl/go/go${GOLANG_VERSION}.linux-amd64.tar.gz"
      - tar -xvzf "go${GOLANG_VERSION}.linux-amd64.tar.gz"
      - mv go/ /opt
      - export PATH="/opt/go/bin/":$PATH
      - mkdir -p /tmp/${PACKAGE}
      - mv ${CODEBUILD_SRC_DIR}/* /tmp/${PACKAGE}
      - mv "/tmp/$(echo ${PACKAGE} | cut -d '/' -f1)" ${CODEBUILD_SRC_DIR}/
  pre_build:
    commands:
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - export PATH="/opt/go/bin/":$PATH
      - cd ${CODEBUILD_SRC_DIR}/${PACKAGE}
      - make build_production
      - docker build -t $IMAGE_REPO_NAME:latest .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
